# Generated by Django 4.0.5 on 2023-06-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('which_department', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('person_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendanceApp.staffs')),
            ],
            options={
                'verbose_name_plural': 'Visitors',
            },
        ),
    ]
